### ISSUE TITLE
No `AndroidManifest.xml` file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#21]
Hi,

Now with android `7.1.4` there is no `AndroidManifest.xml` file. So can you tell me how to add  ` android:largeHeap="true"` there?

**Comment by eddyfrank** [comment]
There is always an `AndroidManifest.xml` file:

**`platforms/android/app/src/main/AndroidManifest.xml`**


Please consider checking Cordova docs and release notes, like this one:
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

I kindly ask you not to opening issues about general Cordova development questions. Such questions are not related to Scanbot SDK or this example app.

While we are always happy to help our (potential) customers with issues, we unfortunately have to limit the support to issues which are directly caused by the Scanbot SDK.
This is due to the fact that we try to help as many customers as possible, always with very short reaction times. I hope you understand our reasoning there.

**Comment by Sampath-Lokuge** [comment]
Then please update your doc to reflect that. It says this `platforms/android/AndroidManifest.xml`. There is no such path on latest android. Do is this: https://scanbotsdk.github.io/documentation/cordova/

@eddyfrank

**Comment by eddyfrank** [comment]
Thanks for the hint. We have updated our docs.
The path mentioned in the docs was for the minimum required version 6.4 of the `cordova-android` platform.

(But the actual point is, that in app development the things are going very fast and developers must be able to adopt them  😉 ).

**Comment by Sampath-Lokuge** [comment]
Yes, That is why we always refer to the official doc. Your responsibility is to update it according to the latest ecosystem changes. Since this is paid plugin you must always do that. Because we paid for this. We don't have time to refer all the documents which are related to Cordova ecosystem. We always open the ionic doc and the related Cordova plugin doc. That is it. If those docs are not working we log an issue. Then they'll see those issues and update the docs and etc. But it seems your world is different and not suitable for the public repository like git. Sorry, I'm very disappointed with your feedback and attitude. @eddyfrank
