### ISSUE TITLE
UnsatisfiedLinkError on a 64 bit device - with a workaround

### ISSUE THREAD

**Issue by AndrWeisR** [doo/scanbot-sdk-example-ionic2#5]
When integrating the SDK into an existing Ionic 3 app and deploying the app to a 64 bit device, I got an error on app startup: 

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader... couldn't find "liblept.so"`

This is because of conflicts with other plugins I use which make use of 64 bit native libraries instead of 32 bit libraries (I think it's cordova-sqlite-storage). When the APK is deployed to the 64 bit phone, only the 64 bit libs are present, which doesn't include the "liblept.so" mentioned in the error message.

To work around this, I had to create a `...\platforms\android\build-extras.gradle` file to exclude the 64 bit native libraries from the build, leaving only the 32 bit libraries that include liblept.so.

The `build-extras.gradle` file:

```
android {
    defaultConfig {
        // Remove 64 bit libs (arm64-v8a and x86_64) for Scanbot.
        // The 64 bit libs don't include liblept.so, which Scanbot requires.
        // if the 64 bit libs are present, they will be the only ones used when the APK
        // is deployed to a 64 bit device.
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}
```

**Comment by eddyfrank** [comment]
The Scanbot SDK uses native libraries under the hood and supports the ABIs `armeabi-v7a` and `x86`. We don't provide an explicit lib (.so file) for the "arm64" architectures, since our `armeabi-v7a` library is fully compatible with "arm64". So you can run Scanbot SDK on all "arm64" devices too.
It is important to adjust the ABI settings of your project accordingly:

```
ndk {
  abiFilters "armeabi-v7a", "x86"
}
```

You have to exclude the "arm64" ABI from the settings in your build.gradle file. Otherwise the APK will contain the "arm64" folder and your app will try to search for Scanbot libs in it.
If you exclude "arm64" libs, other 3rd party libs will also use their "armeabi-v7a" libs as fallback.

Please also note:
- A production build would typically also exclude `x86`, since it is used for emulators.
- `mips` is not supported, since it is used by very old devices (it is also marked as deprecated by Google/Android).
