### ISSUE TITLE
Invalid image URI

### ISSUE THREAD

**Issue by RikdeVos** [doo/scanbot-sdk-example-ionic2#6]
The app runs great and I can detect documents in the viewfinder, but after capturing a photo it appears blank in the UI. The image source is returned a 404. Pressing "Start Cropping UI" after I have taken a photo does show a popover with the correct photo, so it's saved correctly.

Platform: iOS 11.2.6
Cordova ios 4.5.4

**Comment by eddyfrank** [comment]
@RikdeVos , do you use `WKWebView`?
For `WKWebView` please make sure to use a file **path** ("/some/image/file.jpg") instead of a file **URI** ("file:///some/image/file.jpg") returned by Scanbot Plugin.

Also see 

- "Native files not loading correctly" in this article https://blog.ionicframework.com/wkwebview-for-all-a-new-webview-for-ionic/

- and our example fix here https://github.com/doo/scanbot-sdk-example-ionic2/blob/master/src/pages/sdk-ui/sdk-ui.html#L22

**Comment by RikdeVos** [comment]
I am not using WKWebView, I've simply cloned this repo and are running it on an iOS device, so it should be easy to replicate. I can probably easily get it to work, but wanted to let you know that this example app is not fully working out of the box.
